---
abstract: 'Distributed socket server framework'
author:
  - 'Adi Seredinschi <adizere@cpan.org>'
build_requires:
  Attribute::Abstract: 1.0
  Class::Accessor::Grouped: 0.1
  Exporter: 5.6
  File::Temp: 0.2
  IO::Socket::SSL: 1.6
  JSON: 2.53
  Test::Deep: 0.1
  Test::Exception: 0.3
  Test::File: 1.3
  Test::MockModule: 0.05
  Test::More: 0.9
configure_requires:
  Module::Build: 0.38
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Odin
provides:
  Odin:
    file: lib/Odin.pm
    version: 0.001
  Odin::ProtocolStack:
    file: lib/Odin/ProtocolStack.pm
  Odin::ProtocolStack::Configuration:
    file: lib/Odin/ProtocolStack/Configuration.pm
  Odin::ProtocolStack::Layer:
    file: lib/Odin/ProtocolStack/Layer.pm
  Odin::ProtocolStack::Layer::Dispatcher:
    file: lib/Odin/ProtocolStack/Layer/Dispatcher.pm
  Odin::ProtocolStack::Layer::Messaging:
    file: lib/Odin/ProtocolStack/Layer/Messaging.pm
  Odin::ProtocolStack::Layer::Socket:
    file: lib/Odin/ProtocolStack/Layer/Socket.pm
  Odin::ProtocolStack::Message:
    file: lib/Odin/ProtocolStack/Message.pm
  Odin::ProtocolStack::Message::JSONEncoded:
    file: lib/Odin/ProtocolStack/Message/JSONEncoded.pm
  Odin::ProtocolStack::ProtocolClass:
    file: lib/Odin/ProtocolStack/ProtocolClass.pm
  Odin::ProtocolStack::Resource:
    file: lib/Odin/ProtocolStack/Resource.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
